[[D-manual-info]]
[appendix]
== How this manual is created

The content of this manual is written using a framework named https://asciidoctor.org/[Asciidoctor]

--
Asciidoctor is a fast, open source text processor and publishing toolchain for converting AsciiDoc content to HTML5, DocBook, PDF, and other formats. Asciidoctor is written in Ruby and runs on all major operating systems. The Asciidoctor project is hosted on GitHub.
--

Asciidoctor reads and parses text written in the AsciiDoc syntax, then feeds the parse tree to a set of built-in converters to produce HTML5, DocBook 5, and man(ual) page output.

Using the asciidoctor framework and its plugins the content of this manual source is converted into HTML5, EPUB and PDF document.  The diarams which are written in PlantUML format are converted into images by using asciidoctor-diagram plugin

=== How to build the manual

==== Ensure podman machine is having access to user home

[source, bash]
----
podman machine init --cpus=4 --disk-size=60 --memory=6096 -v $HOME:$HOME
----

==== Pull the image for use

[source, bash]
----
podman pull --platform linux/arm64 docker.io/asciidoctor/docker-asciidoctor # Apple M1 arm64
podman pull docker.io/asciidoctor/docker-asciidoctor
----

==== Build manual using podman container

[source, bash]
----
./manual/podmanbuild.sh
----
