=== Open Close Principle
(((Open Close Principle)))
--
.Bertrand Mayer definition

From his 1988 book, Object-Oriented Software Construction (Prentice Hall), defined the open/closed principle (OCP) as follows:

Software entities should be open for extension, but closed for modification.
--

--
.Robert C. Martin definition

“Open for extension.” This means that the behavior of the module can be extended. As the requirements of the application change, we are able to extend the module with new behaviors that satisfy those changes. In other words, we are able to change what the module does.

“Closed for modification.” Extending the behavior of a module does not result in changes to the source or binary code of the module. The binary executable version of the module, whether in a linkable library, a DLL, or a Java .jar, remains untouched.

—Robert C. Martin, Agile Software Development: Principles, Patterns, and Practices (Prentice Hall, 2003)
--

Open Close Principle advocates class to be open for extension but closed for modifications.  To enhance the functionality the design should allow additions of new functionality by adding new files to the code, instead of modifying an existing file.

==== Switch Unclean Example
(((Open Close Principle, Switch Unclean)))
The logic in the example below in `DiscountCalculator` is based on month number.  For different months we need discount to be calculated with some rules.  For addition of new rules or modification of any existing rule we will have to change the file `DiscountCalculator` and hence this file violates the open close principle.

Just to change one rule if we touch the file `DiscountCalculator` we will have to regression test all the rules to make sure nothing is broken in other parts which are also in the same file.

==== UML Representation

[plantuml, switch-unclean, png]
----
class DiscountCalculator {
    double calculateDiscount(double amount, int month)
}
class Application
DiscountCalculator <-- Application
----

[source,java]
----
include::../../../../ch01-solid-principles/s02-open-close/ex01-switch-unclean/src/main/java/com/example/DiscountCalculator.java[tags=source]
----

[source,java]
----
include::../../../../ch01-solid-principles/s02-open-close/ex01-switch-unclean/src/test/java/com/example/DiscountCalculatorTest.java[tags=source]
----

==== Switch clean version
(((Open Close Principle, Switch Clean Version)))
In this version we extracted the logic of calculating the discount into separate classes implementing same interface.  The map of all such strategies will maintain what rule we want to use for certain month.

If we need to change an existing rule only one existing class needs changes and the rest of the rules need no testing as they were not changed.

For addition of new rule we need to add a new class implementation of strategy and add it to the map.  Again retesting of existing rules is not needed, as `DiscountCalculator` class is now open to extension but closed to modification.

==== UML Representation

[plantuml, switch-clean, png]
----
interface IDiscountStrategy {
    +double calculateDiscount(double amount, int month)
}
class DiscountCalculator {
    double calculateDiscount(double amount, int month)
}
class JanFebDiscountStrategy
class AugDiscountStrategy
class OtherDiscountStrategy
class Application
IDiscountStrategy <|.. JanFebDiscountStrategy
IDiscountStrategy <|.. AugDiscountStrategy
IDiscountStrategy <|.. OtherDiscountStrategy
DiscountCalculator --> IDiscountStrategy
DiscountCalculator <-- Application

----

[source,java]
----
include::../../../../ch01-solid-principles/s02-open-close/ex02-switch-clean/src/main/java/com/example/DiscountCalculator.java[tags=source]
----
<1> Get strategy object for given month

[source,java]
----
include::../../../../ch01-solid-principles/s02-open-close/ex02-switch-clean/src/main/java/com/example/IDiscountStrategy.java[tags=source]
----

[source,java]
----
include::../../../../ch01-solid-principles/s02-open-close/ex02-switch-clean/src/main/java/com/example/strategies/DiscountStrategyMap.java[tags=source]
----

[source,java]
----
include::../../../../ch01-solid-principles/s02-open-close/ex02-switch-clean/src/main/java/com/example/strategies/JanFebDiscountStrategy.java[tags=source]
----

[source,java]
----
include::../../../../ch01-solid-principles/s02-open-close/ex02-switch-clean/src/main/java/com/example/strategies/AugDiscountStrategy.java[tags=source]
----

[source,java]
----
include::../../../../ch01-solid-principles/s02-open-close/ex02-switch-clean/src/main/java/com/example/strategies/OtherDiscountStrategy.java[tags=source]
----